[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cauda"
version = "0.1.0"
description = "cauda package"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["cauda"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
