# data
dim: 10
n_samples_train: 30_000
n_samples_test: 10_000
target_data_type: alpha_stable
stable_alpha_data: 1.8

# averaging
n_trials: 5
seed: 0

# generator
asinh_scale: 1.0
stable_alpha_model: 1.8
n_steps: 150
barron_alphas: [2.0, 1.0, 0.0, -10000.0]

# neural net
depth: 4
width: 64
batch_size: 1024
n_epochs: 150
lr: 0.001
grad_clip_norm: null
use_adamw: false
num_workers: 0

# general
device: auto
fdtype: float32
idtype: int32
